version: "3"
services:
  web:
    container_name: web_server
    build: ./web_server
    volumes:
      - ./web_server/php:/var/www/app
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - docker_net

  db:
    container_name: mysql_server
    build: ./db_server
    volumes:
      - ./db_server/db_volume:/var/lib/mysql
      - ./db_server/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: 'Asia/Tokyo'
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge